"""add sha256 and received_at to file_records

Revision ID: 272465ebd1ab
Revises: 001
Create Date: 2025-12-13 21:20:21.418785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '272465ebd1ab'
down_revision = '001'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('file_records', sa.Column('sha256', sa.String(), nullable=True))
    op.add_column('file_records', sa.Column('received_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False))
    op.create_index(op.f('ix_file_records_sha256'), 'file_records', ['sha256'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_file_records_sha256'), table_name='file_records')
    op.drop_column('file_records', 'received_at')
    op.drop_column('file_records', 'sha256')
    # ### end Alembic commands ###

